plugins:
  - serverless-python-requirements

service: ${opt:stage}-function

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaulStage}
  deploymentBucket:
    name: xxx-zzz-sample
  memorySize: 128

custom:
  defaultStage: dev

functions:
  lambda_function:
    handler: handler.lambda_handler
    name: dev-function
    role: arn:aws:iam:713881825349:role/lambda-test-role
    disableLogs: true
    timeout: 900
