plugins:
  - serverless-step-functions

service: ${opt:stage}-stepfunction

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaulStage}
  deploymentBucket:
    name: xxx-zzz-sample
  memorySize: 128

custom:
  defaultStage: dev

stepFunctions:
  stateMachines:
    step1:
      name: dev-stepfunction
      role: arn:aws:iam::713881825349:role/stepfunctions-test-role
      definition:
        StartAt: test1
        States:
          test1:
            Type: Task
            Resource: arn:aws:states:::lambda:invoke
            Parameters:
              FunctionName: "arn:aws:lambda:ap-northeast-1:713881825349:function:dev-function"
            End: true
