name: serverless
run-name: serverless

on:
  workflow_dispatch:
    inputs:
      target_env_name:
        type: choice
        description: dev
        required: true
        options: [dev]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: check out
        uses: actions/checkout@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHunActions-${{ github.run_id }}
          aws-region: ap-northeast-1

      - name: Serverless Deploy
        working-directory: ./serverless
        run: |
          npm install -g serverless@2
          npm install -g serverless-step-functions
          npm install -g serverless-python-requirements
          npm install -g serverless-lambda-layers
          
          srverless deploy -V --stage dev